#!/usr/bin/env bash
# PreToolUse:Edit|Write|MultiEdit — protect sensitive files from agent edits.
# Ratchets are only written by commit hooks, never by the agent directly.

set -euo pipefail

INPUT=$(cat)
FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.path // ""' 2>/dev/null || echo "")

if [[ -z "$FILE" ]]; then
  exit 0
fi

case "$FILE" in
  */.env|*/.env.*|*.env.local|*.env.production|*.env.staging)
    {
      echo "Blocked: .env files contain secrets and must not be edited by the agent."
      echo "Fix: add the new variable to the appropriate .env.example template, then have the developer copy + fill in their local .env."
    } >&2
    exit 2
    ;;
  */bun.lockb|*/bun.lock|*/uv.lock|*/package-lock.json|*/pnpm-lock.yaml|*/Cargo.lock|*/poetry.lock)
    {
      echo "Blocked: lockfiles are generated by the package manager, not hand-edited."
      echo "Fix: run the install command instead (e.g., 'uv add <pkg>' / 'bun add <pkg>' / 'bun install') and commit the resulting lockfile."
    } >&2
    exit 2
    ;;
  */.claude/ratchet/*.json)
    {
      echo "Blocked: ratchet files are written by commit hooks, not by the agent."
      echo "Fix: if you intend to relax the floor, discuss with the team first; otherwise fix the regression in code instead."
    } >&2
    exit 2
    ;;
  */.claude/state/phase)
    {
      echo "Blocked: direct edits to .claude/state/phase bypass the TDD phase mirror contract."
      echo "Rule: the phase file is owned by eneo_phase_set, which updates current-task.json first and the mirror second."
      echo "Fix: source hooks/lib/state.sh and call 'eneo_phase_set RED|GREEN|REFACTOR|FREE' instead of editing the file directly."
    } >&2
    exit 2
    ;;
esac

exit 0
